version: "3"
services:
  ibge-api:
    image: ${DOCKER_REGISTRY-}ibge-api
    build:
      context: ./src
      dockerfile: ./Balta.IBGE.Api/Dockerfile
    ports:
      - 8083:80
      - 8084:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
      - redis
    networks:
      - balta
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=wq5p5*YQ#N
    networks:
      - balta

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - balta

networks:
  balta:
    driver: bridge